// Auto-generated by scripts/genFlowsVersions.ts — do not edit manually.
// Regenerate with `bun scripts/genFlowsVersions.ts` after bumping @qawolf/flows.
export const flowsVersion = "0.1.1";
export const playwrightVersion = "1.58.2";
