// Verbatim project-file bodies ported from cli-test/ cases 01–08. Each string
// reproduces the on-disk file byte-for-byte (trailing newline included) so a
// materialized shape matches the cli-test tree exactly.

export const npmSinglePackageJson = `{ "name": "npm-single", "type": "module", "version": "1.0.0" }\n`;

export const bunSinglePackageJson = `{ "name": "bun-single", "type": "module", "version": "1.0.0" }\n`;

// Shared by the bun single-package (03) and bun workspace (07) shapes.
export const bunLock = `{
  "lockfileVersion": 1,
  "workspaces": {},
  "packages": {}
}
`;

export const nativeVersionedPackageJson = `{
  "name": "native-versioned",
  "type": "module",
  "version": "1.0.0",
  "dependencies": {
    "diff": "^8.0.3",
    "sharp": "0.34.3"
  }
}
`;

export const npmWorkspaceRootPackageJson = `{ "name": "npm-ws-root", "private": true, "workspaces": ["packages/*"] }\n`;

export const yarnWorkspaceRootPackageJson = `{ "name": "yarn-ws-root", "private": true, "workspaces": ["packages/*"] }\n`;

export const bunWorkspaceRootPackageJson = `{ "name": "bun-ws-root", "private": true, "workspaces": ["packages/*"] }\n`;

export const pnpmWorkspaceRootPackageJson = `{ "name": "pnpm-ws-root", "private": true }\n`;

export const pnpmWorkspaceYaml = `packages:\n  - "packages/*"\n`;

export const pnpmLock = `lockfileVersion: '9.0'\n`;

export const yarnLock = `# THIS IS AN AUTOGENERATED FILE.\n__metadata:\n  version: 8\n`;

// Shared leaf-package manifest for every workspace shape (04–07).
export const workspaceAppPackageJson = `{ "name": "@ws/app", "type": "module", "version": "1.0.0" }\n`;
