import { type Command, Help } from "commander";

import { getCommandKind } from "./commandKind.js";

const commandsTableStartMarker =
  "<!-- commands-table:start — generated by `bun run generate`, do not edit -->";
const commandsTableEndMarker = "<!-- commands-table:end -->";

function listVisibleLeaves(
  command: Command,
  prefix: string[],
): { command: Command; path: string[] }[] {
  const children = new Help()
    .visibleCommands(command)
    .filter((child) => child.name() !== "help");
  const self = prefix.length > 0 ? [{ command, path: prefix }] : [];
  if (children.length === 0) return self;
  // A command that has subcommands but also runs on its own (e.g. `install`)
  // gets its own row in addition to its children.
  const runsItself =
    prefix.length > 0 && command.registeredArguments.length > 0;
  return [
    ...(runsItself ? self : []),
    ...children.flatMap((child) =>
      listVisibleLeaves(child, [...prefix, child.name()]),
    ),
  ];
}

function resolveKind(command: Command, path: string): string {
  const kind = getCommandKind(command);
  if (kind === undefined) {
    throw new Error(
      `Command "${path}" has no kind. Declare it with declareCommandKind where the command is defined.`,
    );
  }
  return kind;
}

function renderTable(rows: string[][]): string {
  const header = ["Command", "Kind", "What it does"];
  const all = [header, ...rows];
  const widths = header.map((_, column) =>
    Math.max(...all.map((row) => (row[column] ?? "").length)),
  );
  const renderRow = (row: string[]) =>
    `| ${row.map((cell, column) => cell.padEnd(widths[column] ?? 0)).join(" | ")} |`;
  const divider = `| ${widths.map((width) => "-".repeat(width)).join(" | ")} |`;
  return [renderRow(header), divider, ...rows.map(renderRow)].join("\n");
}

export function renderCommandsTable(program: Command): string {
  const rows = listVisibleLeaves(program, [])
    .map(({ command, path }) => ({ command, path: path.join(" ") }))
    .sort((left, right) => left.path.localeCompare(right.path))
    .map(({ command, path }) => [
      `\`qawolf ${path}\``,
      resolveKind(command, path),
      command.description(),
    ]);
  return renderTable(rows);
}

export function spliceCommandsTable(skillMd: string, table: string): string {
  const start = skillMd.indexOf(commandsTableStartMarker);
  const end = skillMd.indexOf(commandsTableEndMarker);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      "skills/qawolf-cli/SKILL.md is missing the commands-table markers.",
    );
  }
  const before = skillMd.slice(0, start + commandsTableStartMarker.length);
  const after = skillMd.slice(end);
  return `${before}\n\n${table}\n\n${after}`;
}
