import { type Command, Help } from "commander";
import { publicContractsV1 } from "@qawolf/api-contracts/v1";

import { buildCommandSpecs } from "~/domains/publicApi/commandSpecs.js";

const commandsTableStartMarker =
  "<!-- commands-table:start — generated by `bun run generate`, do not edit -->";
const commandsTableEndMarker = "<!-- commands-table:end -->";

// `read` calls the QA Wolf API without changing anything; `write` changes
// team state; `local` only affects this machine.
type CommandKind = "read" | "write" | "local";

// Public API commands derive read/write from their contract. Every other
// command must be classified here; rendering throws on a missing entry so a
// new command cannot ship unclassified.
const localCommandKinds: Record<string, CommandKind> = {
  "auth login": "local",
  "auth logout": "local",
  "auth whoami": "read",
  doctor: "local",
  "flows list": "local",
  "flows pull": "read",
  "flows run": "local",
  init: "local",
  install: "local",
  "install android": "local",
  "install browsers": "local",
};

function listVisibleLeaves(
  command: Command,
  prefix: string[],
): { path: string[]; description: string }[] {
  const children = new Help()
    .visibleCommands(command)
    .filter((child) => child.name() !== "help");
  const self =
    prefix.length > 0
      ? [{ path: prefix, description: command.description() }]
      : [];
  if (children.length === 0) return self;
  // A command that has subcommands but also runs on its own (e.g. `install`)
  // gets its own row in addition to its children.
  const runsItself =
    prefix.length > 0 && command.registeredArguments.length > 0;
  return [
    ...(runsItself ? self : []),
    ...children.flatMap((child) =>
      listVisibleLeaves(child, [...prefix, child.name()]),
    ),
  ];
}

function resolveKind(path: string): CommandKind {
  const contractKinds = new Map(
    buildCommandSpecs(publicContractsV1).map((spec) => [
      spec.commandPath.join(" "),
      spec.kind,
    ]),
  );
  const kind = contractKinds.get(path) ?? localCommandKinds[path];
  if (kind === undefined) {
    throw new Error(
      `Command "${path}" has no kind. Classify it in localCommandKinds (src/commands/skill.ts).`,
    );
  }
  return kind;
}

function renderTable(rows: string[][]): string {
  const header = ["Command", "Kind", "What it does"];
  const all = [header, ...rows];
  const widths = header.map((_, column) =>
    Math.max(...all.map((row) => (row[column] ?? "").length)),
  );
  const renderRow = (row: string[]) =>
    `| ${row.map((cell, column) => cell.padEnd(widths[column] ?? 0)).join(" | ")} |`;
  const divider = `| ${widths.map((width) => "-".repeat(width)).join(" | ")} |`;
  return [renderRow(header), divider, ...rows.map(renderRow)].join("\n");
}

export function renderCommandsTable(program: Command): string {
  const rows = listVisibleLeaves(program, [])
    .map(({ path, description }) => ({ path: path.join(" "), description }))
    .sort((left, right) => left.path.localeCompare(right.path))
    .map(({ path, description }) => [
      `\`qawolf ${path}\``,
      resolveKind(path),
      description,
    ]);
  return renderTable(rows);
}

export function spliceCommandsTable(skillMd: string, table: string): string {
  const start = skillMd.indexOf(commandsTableStartMarker);
  const end = skillMd.indexOf(commandsTableEndMarker);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      "skills/qawolf-cli/SKILL.md is missing the commands-table markers.",
    );
  }
  const before = skillMd.slice(0, start + commandsTableStartMarker.length);
  const after = skillMd.slice(end);
  return `${before}\n\n${table}\n\n${after}`;
}
