import type { Command } from "commander";

import { getCommandKind } from "./commandKind.js";
import { findSubcommand, listVisibleSubcommands } from "./help/commandTree.js";
import { renderHelpReference } from "./help/reference.js";

const commandsTableStartMarker =
  "<!-- commands-table:start — generated by `bun run generate`, do not edit -->";
const commandsTableEndMarker = "<!-- commands-table:end -->";
const runnerReferenceHeader =
  "<!-- Generated by `bun run generate` from `qawolf help ref runner`, do not edit. Edit the runner commands' help under src/commands/runner instead. -->";

function listVisibleLeaves(
  command: Command,
  prefix: string[],
): { command: Command; path: string[] }[] {
  const children = listVisibleSubcommands(command);
  const self = prefix.length > 0 ? [{ command, path: prefix }] : [];
  if (children.length === 0) return self;
  // A command that has subcommands but also runs on its own (e.g. `install`)
  // gets its own row in addition to its children.
  const runsItself =
    prefix.length > 0 && command.registeredArguments.length > 0;
  return [
    ...(runsItself ? self : []),
    ...children.flatMap((child) =>
      listVisibleLeaves(child, [...prefix, child.name()]),
    ),
  ];
}

function resolveKind(command: Command, path: string): string {
  const declared = getCommandKind(command);
  if (declared === undefined) {
    throw new Error(
      `Command "${path}" has no kind. Declare it with declareCommandKind where the command is defined.`,
    );
  }
  return declared.kindNote === undefined
    ? declared.kind
    : `${declared.kind} (${declared.kindNote})`;
}

// Cells stay unpadded: column alignment costs tokens on every skill
// activation (the widest cell would pad all rows to its width) and
// markdown renders unaligned tables identically. The prettier-ignore
// comment keeps oxfmt from re-padding the table; oxfmt wants it
// directly above the table, with no blank line between.
function renderTable(rows: string[][]): string {
  const header = ["Command", "Kind", "What it does"];
  const renderRow = (row: string[]) => `| ${row.join(" | ")} |`;
  const divider = `| ${header.map(() => "---").join(" | ")} |`;
  return [
    "<!-- prettier-ignore -->",
    renderRow(header),
    divider,
    ...rows.map(renderRow),
  ].join("\n");
}

export function renderCommandsTable(program: Command): string {
  const rows = listVisibleLeaves(program, [])
    .map(({ command, path }) => ({ command, path: path.join(" ") }))
    .sort((left, right) => left.path.localeCompare(right.path))
    .map(({ command, path }) => [
      `\`qawolf ${path}\``,
      resolveKind(command, path),
      command.description(),
    ]);
  return renderTable(rows);
}

export function spliceCommandsTable(skillMd: string, table: string): string {
  const start = skillMd.indexOf(commandsTableStartMarker);
  const end = skillMd.indexOf(commandsTableEndMarker);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      "skills/qawolf-cli/SKILL.md is missing the commands-table markers.",
    );
  }
  const before = skillMd.slice(0, start + commandsTableStartMarker.length);
  const after = skillMd.slice(end);
  return `${before}\n\n${table}\n\n${after}`;
}

/** skills/qawolf-cli/references/runner.md: `qawolf help ref runner`, kept as a file for agents that cannot run the CLI. */
export function renderRunnerReferenceMd(program: Command): string {
  const runner = findSubcommand(program, ["runner"]);
  if (runner === undefined) throw new Error("qawolf has no runner command.");
  return `${runnerReferenceHeader}\n\n${renderHelpReference(runner, ["qawolf", "runner"])}`;
}
