import type { AnyPublicApiContract } from "@qawolf/api-contracts/v1";

import { buildOutputFieldDocs } from "~/core/publicApi/outputFields.js";

const fieldsStartMarker =
  "<!-- fields:start — generated by `bun run generate`, do not edit -->";
const fieldsEndMarker = "<!-- fields:end -->";

// Bullets rather than a table: descriptions are full sentences, so table pipes
// and alignment would cost tokens on every read without aiding a reader.
export function renderResponseFields(contract: AnyPublicApiContract): string {
  const fields = buildOutputFieldDocs(contract.output);
  if (fields.length === 0) {
    throw new Error(
      `Contract "${contract.name}" documents no response field; the reference would be empty.`,
    );
  }
  return fields
    .map((field) => `- \`${field.path}\` — ${field.description}`)
    .join("\n");
}

export function spliceResponseFields(
  template: string,
  rendered: string,
): string {
  const start = template.indexOf(fieldsStartMarker);
  const end = template.indexOf(fieldsEndMarker);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      "skills/qawolf-cli/references/run-results.md is missing the fields markers.",
    );
  }
  const before = template.slice(0, start + fieldsStartMarker.length);
  const after = template.slice(end);
  return `${before}\n\n${rendered}\n\n${after}`;
}
