import { describe, expect, it } from "bun:test";
import { publicContractsV1 } from "@qawolf/api-contracts/v1";
import { join } from "node:path";
import { z } from "zod";

import {
  renderResponseFields,
  spliceResponseFields,
} from "./skillRunResults.js";

const runResultsMdPath = join(
  import.meta.dirname,
  "../../skills/qawolf-cli/references/run-results.md",
);
const runResultsTemplatePath = join(
  import.meta.dirname,
  "qawolfCliRunResults.template.md",
);

describe("renderResponseFields", () => {
  it("renders one bullet per documented field", () => {
    const contract = {
      description: "Look up a run.",
      input: z.object({ runId: z.string() }),
      kind: "read",
      name: "run.get",
      output: z.object({
        runId: z.string().describe("The id of the run."),
        internal: z.string(),
      }),
    } as const;

    expect(renderResponseFields(contract)).toBe(
      "- `runId` — The id of the run.",
    );
  });

  it("throws when the contract documents nothing, rather than emitting an empty reference", () => {
    const contract = {
      description: "Look up a run.",
      input: z.object({ runId: z.string() }),
      kind: "read",
      name: "run.get",
      output: z.object({ runId: z.string() }),
    } as const;

    expect(() => renderResponseFields(contract)).toThrow(
      'Contract "run.get" documents no response field',
    );
  });

  it("documents the artifact urls and the nested attempt paths", () => {
    const rendered = renderResponseFields(publicContractsV1.run.get);

    expect(rendered).toContain(
      "- `flows[].attempts[].traceUrl` — Signed URL for the attempt's Playwright trace",
    );
    expect(rendered).toContain("- `flows[].attempts[].logsUrl`");
    expect(rendered).toContain("- `flows[].attempts[].videoUrl`");
    expect(rendered).toContain("- `flows[].attempts[].status` — One of:");
  });
});

describe("spliceResponseFields", () => {
  it("replaces the marked region, keeping the surrounding prose", () => {
    const template = [
      "# Run results",
      "<!-- fields:start — generated by `bun run generate`, do not edit -->",
      "stale",
      "<!-- fields:end -->",
      "trailing prose",
    ].join("\n");

    const spliced = spliceResponseFields(template, "- `runId` — The id.");

    expect(spliced).toContain("# Run results");
    expect(spliced).toContain("- `runId` — The id.");
    expect(spliced).toContain("trailing prose");
    expect(spliced).not.toContain("stale");
  });

  it("throws when the template has no markers", () => {
    expect(() => spliceResponseFields("# Run results", "x")).toThrow(
      "is missing the fields markers",
    );
  });
});

describe("run-results reference", () => {
  // Fails the moment @qawolf/api-contracts changes run.get's documented
  // fields, which is what keeps this file from drifting from the installed CLI.
  it("matches its template and the published contract", async () => {
    const runResultsMd = await Bun.file(runResultsMdPath).text();
    const template = await Bun.file(runResultsTemplatePath).text();

    expect(runResultsMd).toBe(
      spliceResponseFields(
        template,
        renderResponseFields(publicContractsV1.run.get),
      ),
    );
  });
});
