#!/usr/bin/env bun
// Reads installed package versions and writes version constants used by
// pinnedPackages.ts. Run automatically via the prepare hook; re-run manually
// after bumping any of these packages.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..");

// Exported constant name → package to read the installed version from. Every
// package here is a devDependency: the CLI never imports these at runtime, it
// installs them into the managed runtime dir, and listing them as dependencies
// would leak their peer graphs into `npm i @qawolf/cli`. See pinnedPackages.ts.
const versionSources = {
  flowsVersion: "@qawolf/flows",
  playwrightVersion: "playwright",
  emailsVersion: "@qawolf/emails",
  testkitVersion: "@qawolf/testkit",
  appiumVersion: "appium",
  appiumUiautomator2DriverVersion: "appium-uiautomator2-driver",
  expectWebdriverioVersion: "expect-webdriverio",
  webdriverioVersion: "webdriverio",
  wdioGlobalsVersion: "@wdio/globals",
  wdioLoggerVersion: "@wdio/logger",
} as const;

function readVersion(pkgName: string): string {
  const raw = readFileSync(
    join(root, "node_modules", pkgName, "package.json"),
    "utf8",
  );
  return (JSON.parse(raw) as { version: string }).version;
}

const versions = Object.entries(versionSources).map(
  ([constName, pkgName]) => [constName, pkgName, readVersion(pkgName)] as const,
);

const out = [
  "// Auto-generated by scripts/genDependencyVersions.ts — do not edit manually.",
  "// Regenerate with `bun scripts/genDependencyVersions.ts` after bumping any pinned package.",
  ...versions.map(
    ([constName, , version]) => `export const ${constName} = "${version}";`,
  ),
  "",
].join("\n");

const outDir = join(root, "src/generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "dependencyVersions.ts"), out);
console.log(
  `Generated src/generated/dependencyVersions.ts: ${versions
    .map(([, pkgName, version]) => `${pkgName}=${version}`)
    .join(" ")}`,
);
