#!/usr/bin/env bun
// Reads installed package versions and writes version constants used by
// ensureDeps.ts. Run automatically via the prepare hook; re-run manually
// after bumping any of these packages.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..");

function readVersion(pkgName: string): string {
  const raw = readFileSync(
    join(root, "node_modules", pkgName, "package.json"),
    "utf8",
  );
  return (JSON.parse(raw) as { version: string }).version;
}

const flowsVersion = readVersion("@qawolf/flows");
const playwrightVersion = readVersion("playwright");
const emailsVersion = readVersion("@qawolf/emails");
const testkitVersion = readVersion("@qawolf/testkit");
const appiumVersion = readVersion("appium");
const appiumXcuitestDriverVersion = readVersion("appium-xcuitest-driver");
const appiumUiautomator2DriverVersion = readVersion(
  "appium-uiautomator2-driver",
);

const out = [
  "// Auto-generated by scripts/genDependencyVersions.ts — do not edit manually.",
  "// Regenerate with `bun scripts/genDependencyVersions.ts` after bumping any pinned package.",
  `export const flowsVersion = "${flowsVersion}";`,
  `export const playwrightVersion = "${playwrightVersion}";`,
  `export const emailsVersion = "${emailsVersion}";`,
  `export const testkitVersion = "${testkitVersion}";`,
  `export const appiumVersion = "${appiumVersion}";`,
  `export const appiumXcuitestDriverVersion = "${appiumXcuitestDriverVersion}";`,
  `export const appiumUiautomator2DriverVersion = "${appiumUiautomator2DriverVersion}";`,
  "",
].join("\n");

const outDir = join(root, "src/generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "dependencyVersions.ts"), out);
console.log(
  `Generated src/generated/dependencyVersions.ts: flows=${flowsVersion} playwright=${playwrightVersion} emails=${emailsVersion} testkit=${testkitVersion} appium=${appiumVersion} xcuitest=${appiumXcuitestDriverVersion} uiautomator2=${appiumUiautomator2DriverVersion}`,
);
