#!/usr/bin/env bun
// Reads the installed @qawolf/flows package.json and writes the version
// constants used by ensureDeps.ts. Run automatically via prebuild hooks;
// re-run manually after bumping @qawolf/flows.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;

const raw: string = readFileSync(
  join(root, "node_modules/@qawolf/flows/package.json"),
  "utf8",
);
const flowsPkg = JSON.parse(raw) as {
  version: string;
  peerDependencies?: Record<string, string>;
};

const flowsVersion = flowsPkg.version;
const playwrightVersion = flowsPkg.peerDependencies?.["playwright"] ?? "";

const out = [
  "// Auto-generated by scripts/genFlowsVersions.ts — do not edit manually.",
  "// Regenerate with `bun scripts/genFlowsVersions.ts` after bumping @qawolf/flows.",
  `export const flowsVersion = "${flowsVersion}";`,
  `export const playwrightVersion = "${playwrightVersion}";`,
  "",
].join("\n");

writeFileSync(join(root, "src/commands/flows/flowsVersions.ts"), out);
console.log(
  `Generated flowsVersions.ts: flows=${flowsVersion} playwright=${playwrightVersion}`,
);
