#!/usr/bin/env bun
// Reads installed package versions and writes version constants used by
// ensureDeps.ts. Run automatically via the prepare hook; re-run manually
// after bumping any of these packages.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;

function readVersion(pkgName: string): string {
  const raw = readFileSync(
    join(root, "node_modules", pkgName, "package.json"),
    "utf8",
  );
  return (JSON.parse(raw) as { version: string }).version;
}

function readFlowsVersion(): { flows: string; playwright: string } {
  const raw = readFileSync(
    join(root, "node_modules/@qawolf/flows/package.json"),
    "utf8",
  );
  const pkg = JSON.parse(raw) as {
    version: string;
    peerDependencies?: Record<string, string>;
  };
  return {
    flows: pkg.version,
    playwright: pkg.peerDependencies?.["playwright"] ?? "",
  };
}

const { flows: flowsVersion, playwright: playwrightVersion } =
  readFlowsVersion();
const emailsVersion = readVersion("@qawolf/emails");
const testkitVersion = readVersion("@qawolf/testkit");

const out = [
  "// Auto-generated by scripts/genFlowsVersions.ts — do not edit manually.",
  "// Regenerate with `bun scripts/genFlowsVersions.ts` after bumping any pinned package.",
  `export const flowsVersion = "${flowsVersion}";`,
  `export const playwrightVersion = "${playwrightVersion}";`,
  `export const emailsVersion = "${emailsVersion}";`,
  `export const testkitVersion = "${testkitVersion}";`,
  "",
].join("\n");

const outDir = join(root, "src/generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "dependencyVersions.ts"), out);
console.log(
  `Generated src/generated/dependencyVersions.ts: flows=${flowsVersion} playwright=${playwrightVersion} emails=${emailsVersion} testkit=${testkitVersion}`,
);
